---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Download clickhouse repository key
      become: true
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key"
        dest: "/etc/apt/keyrings/clickhouse.asc"
        mode: "0777"
        force: true
    - name: Setup clickhouse key
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/clickhouse.asc] https://packages.clickhouse.com/deb stable main"
        state: present
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        name:
          - clickhouse-client
          - clickhouse-server
        update_cache: true
    - name: Change Listening Address
      become: true
      ansible.builtin.template:
        src: templates/clickhouse-server.j2
        dest: /etc/clickhouse-server/config.d/network.xml
        mode: "0744"
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database, table and user
      ansible.builtin.shell: |
       clickhouse-client -q 'create database if not exists {{ database_name }};'
       clickhouse-client -q "create user if not exists {{ username }} identified by '{{ password }}';"
       clickhouse-client -q "create table if not exists {{ database_name }}.{{ table_name }} {{ table_columns }} engine=Log;"
       clickhouse-client -q "grant all on {{ database_name }}.* to {{ username }};"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db == 0
- name: Install Vector & Install Nginx for simple log generation
  hosts: vector
  handlers:
    - name: Restart Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Install Nginx
      become: true
      ansible.builtin.apt:
        name: nginx
    - name: Install Vector
      become: true
      ansible.builtin.apt:
        deb: "https://packages.timber.io/vector/0.40.0/vector_0.40.0-1_amd64.deb"
    - name: Config Vector
      become: true
      ansible.builtin.template:
        src: templates/vector.j2
        dest: /etc/vector/vector.yaml
        mode: "0744"
      notify: Restart Vector service
- name: Install Nginx & Install Lighthouse & Configure Nginx
  hosts: lighthouse
  handlers:
    - name: Reload Nginx
      become: true
      ansible.builtin.service:
        name: nginx
        state: reloaded
  tasks:
    - name: Install Nginx
      become: true
      ansible.builtin.apt:
        name: nginx
        update_cache: true
    - name: Install Git
      become: true
      ansible.builtin.apt:
        name: git
        update_cache: true
    - name: Install Lighthouse
      become: true
      ansible.builtin.git:
        repo: "https://github.com/VKCOM/lighthouse.git"
        dest: /var/lighthouse
    - name: Config Nginx
      become: true
      ansible.builtin.template:
        src: templates/nginx.j2
        dest: /etc/nginx/sites-available/default
        mode: "0744"
      notify: Reload Nginx
