---
- name: Install Clickhouse
  hosts: clickhouse
  handlers:
    - name: Start clickhouse service
      become: true
      ansible.builtin.service:
        name: clickhouse-server
        state: restarted
  tasks:
    - name: Download clickhouse repository key
      become: true
      ansible.builtin.get_url:
        url: "https://packages.clickhouse.com/rpm/lts/repodata/repomd.xml.key"
        dest: "/etc/apt/keyrings/clickhouse.asc"
        mode: "0777"
    - name: Setup clickhouse key
      become: true
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/clickhouse.asc] https://packages.clickhouse.com/deb stable main"
        state: present
    - name: Install clickhouse packages
      become: true
      ansible.builtin.apt:
        name:
          - clickhouse-client
          - clickhouse-server
        update_cache: true
      notify: Start clickhouse service
    - name: Flush handlers
      ansible.builtin.meta: flush_handlers
    - name: Create database
      ansible.builtin.command: "clickhouse-client -q 'create database logs;'"
      register: create_db
      failed_when: create_db.rc != 0 and create_db.rc !=82
      changed_when: create_db.rc == 0
- name: Install Vector
  hosts: clickhouse
  handlers:
    - name: Restart Vector service
      become: true
      ansible.builtin.service:
        name: vector
        state: restarted
  tasks:
    - name: Install Vector
      become: true
      ansible.builtin.apt:
        deb: "https://packages.timber.io/vector/0.40.0/vector_0.40.0-1_amd64.deb"
    - name: Config Vector
      become: true
      ansible.builtin.template:
        src: templates/vector.j2
        dest: /etc/vector/vector.yaml
        mode: "0744"
      notify: Restart Vector service
